spring:
  application:
    name: 'loja'
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

fornecedor:
  bocker:
    exchange:
      fornecedorEventExchang: fornecedor.fornecedorevent
    queue:
      fornecedorEventQueue:
        name: fornecedor.fornecedorevent.ms.loja

authentication:
  bocker:
    exchange:
      authenticationEventExchang: authentication.authenticationevent
    queue:
      authenticationEventQueue:
        name: authentication.authenticationevent.ms.loja