server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    config:
      import-check:
        enabled: false

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

fornecedor:
  bocker:
    exchange:
      fornecedorEventExchang: fornecedor.fornecedorevent

authentication:
  bocker:
    exchange:
      authenticationEventExchang: authentication.authenticationevent
    queue:
      authenticationEventQueue:
        name: authentication.authenticationevent.ms.fornecedor