spring:
  application:
    name: 'api-gateway'
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: fornecedor
          uri: lb://FORNECEDOR
          predicates:
            - Path=/fornecedor/**
        - id: loja
          uri: lb://LOJA
          predicates:
            - Path=/loja/**
        - id: authentication
          uri: lb://AUTHENTICATION
          predicates:
            - Path=/authentication/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
server:
  port: 5556
