server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/araoalves/arquitetura-springcloud/blob/main/profiles
          search-paths: fornecedor
